version: '2.3'
services:
    aaa-ml-datasets-course-ragilyazev:
        runtime: nvidia
        build:
          context: ./
          dockerfile: ./Dockerfile
          args:
            CONTEXT: 'runtime/devel'
        image: aaa-ml-datasets-course:$USER
        container_name: aaa-ml-datasets-course-$USER
        environment:
            - TZ=MSK
            - PYTHONUNBUFFERED=1
            - JUPYTER_PASSWORD=$JUPYTER_PASSWORD
            - DS_VERTICA_USERNAME=$DS_VERTICA_USERNAME
            - DS_VERTICA_PASSWORD=$DS_VERTICA_PASSWORD
            - DS_VERTICA_PORT=$DS_VERTICA_PORT
            - OMP_NUM_THREADS=8
            - OPENBLAS_NUM_THREADS=8
        ports:
            - "8081:8888"
            - "8061:6006"
        volumes:
            - $ROOT_DIR/aaa-ml-datasets-course:/app
            - $DATA_DIR/aaa-ml-datasets-course:/data
        ipc: host
        shm_size: 16G
        command: /bin/bash -c "cd / && jupyter notebook --allow-root --ip=0.0.0.0"
        restart: unless-stopped